services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - "./sample_data:/usr/share/nginx/html:ro"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
